INSERT INTO Test(TYPE, Contents) VALUES ('bb','Ante3333lope') ON DUPLICATE KEY UPDATE type='bb';


INSERT INTO    DEMANDS(DCODE, DATE, PRICE)
                        VALUES ('005930', '1996-07-06', 700)
                        ON DUPLICATE KEY UPDATE PRICE=VALUES(PRICE)
                        
                        
DESC DEMAND_FOR

SELECT * FROM DEMANDS ORDER BY DATE DESC


SELECT D.DATE, D.PRICE, F.DEMAND_FOR
FROM DEMANDS AS D LEFT JOIN DEMAND_FOR AS F 
ON D.DATE = F.PDATE AND F.UID = 'DGU' AND F.TID='T1'
ORDER BY D.DATE DESC LIMIT 10

WHERE F.UID = 'DGU' AND F.TID='T1'

SELECT * FROM DEMANDS AS D, DEMAND_FOR AS F
WHERE D.DATE = F.PDATE

WHERE F.UID = 'DGU' AND F.TID='T1'


        SELECT D.DATE as DAT, D.PRICE as ACT, IFNULL(S.DISC_RATIO, 0) AS DISC_RATIO, 
		  			IFNULL(ROUND(D.PRICE*S.DISC_RATIO), 0)
        FROM DEMANDS AS D LEFT JOIN SALES AS S 
        ON D.DATE = S.PDATE AND S.UID = 'DGU' AND S.TID='T1' 
        WHERE D.DATE='2024-07-16'
        ORDER BY D.DATE DESC LIMIT 10

SELECT * FROM DEMAND_FOR
WHERE UID = 'DGU' AND TID='T1' AND PDATE > NOW()
ORDER BY PDATE ASC

SELECT PDATE, SCHEDULE FROM PRODUCTIONS
WHERE UID = 'DGU' AND TID='T1'

SELECT * from INVENTORY WHERE UID = 'DGU' AND TID = 'T1' AND QTY>0

SELECT SUM(QTY) AS INVEN FROM INVENTORY


SELECT sum(QTY) FROM INVENTORY WHERE QTY>0 AND
            PROD_DATE < '2024-07-16'
            
            
SELECT I.PROD_DATE, I.QTY, H.SALES_DATE, H.SALES_QTY
FROM INVENTORY AS I LEFT JOIN INVENTORY_HIST AS H
ON I.UID = H.UID AND I.TID = H.TID AND I.PROD_DATE = H.PROD_DATE




select UID, TID, ICON_URL, 
(SELECT SUM(AMOUNT) FROM LEDGER AS L WHERE L.UID=T.UID AND L.TID=T.TID) AS CUR_BALANCE
from TEAMS T
where STATUS='ACTIVE' order by REG_DATE DESC



SELECT T.UID, T.TID, SUM(L.AMOUNT)
FROM TEAMS AS T LEFT JOIN LEDGER AS L
GROUP BY L.UID, L.TID
ON T.UID=L.UID AND T.TID=L.UID
WHERE T.STATUS='ACTIVE' order BY T.REG_DATE DESC


SELECT date_format(D.DATE, '%Y-%m-%d') as DAT, D.PRICE as ACT, F.DEMAND_FOR as FORC, ABS(D.PRICE-F.DEMAND_FOR) as ABSERR
        FROM DEMANDS AS D LEFT JOIN DEMAND_FOR AS F 
        ON D.DATE = F.PDATE

